### ISSUE TITLE
Support running (most) commands against docker image

### ISSUE THREAD

**Issue by nabadger** [mintel/build-harness#45]
I'm trying to promote running most of our development commands against a docker image.

Typically this would cover 

- Running the site 
- Linting
- Functional Tests
- Unit Tests
- e2e Tests
- Visual Regression Tests
- Coverage
- Container Scanning
- SAST Scanning

- Pipfile locking
- Build docs

We shouldn't require python/pipenv/pytest/python etc to be installed locally to be able to develop an app :)

**Comment by nabadger** [comment]
I was a bit confused about the command that the user would run here.

Would something like the following make sense?

- `make docker/unit-test` 
- `make docker/container-scan`

I know there a `docker` module already, so maybe we could just extend that (or invent a new one)

**Comment by charlieparkes** [comment]
The idea with the modules is that they are a collection of flags/calls for a specific executable rather than just a place we put any command that calls that executable.

So, modules/docker would be boilerplate "generic things you'd want to do with docker" as opposed to "any command that has docker in it." Perhaps we create a new layer for a generic build container (`modules/ci`?) or we put the generic build container calls in language specific layers (`modules/python/Makefile.ci`)? I've only given it a little thought so far, since we need to come up with a good way to do these generic build containers first.

**Comment by nabadger** [comment]
This is perhaps more about how we want to install deps when using build-harness (build-harness-packages, apk, docker (single image vs app-specific).

Closing this for now but will re-open once we decide next steps.
